SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET @OLD_TIME_ZONE=@@TIME_ZONE;
SET TIME_ZONE='-03:00';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;

--
-- Use latin1 when you have accented words even if the database is UTF-8
--
SET NAMES latin1;
--

CREATE SCHEMA IF NOT EXISTS infacademics COLLATE utf8_general_ci ;

ALTER DATABASE infacademics
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE book (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(200) NULL,
  `country` VARCHAR(80) NULL,
  `state` VARCHAR(20) NULL,
  `autor` VARCHAR(150) NULL,
  PRIMARY KEY (`id`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;;

INSERT INTO book VALUES (1,'A volta dos que não foram', 'Brasil', 'RS', 'Fulano de tal');
INSERT INTO book VALUES (2,'O regresso', 'Estados Unidos', 'NY', 'Ciclano de Sousa');